import { type ExperienceItem } from '@/shared/api/generated/portfolio/types';

import { type MainPageLocale } from '../_lib/locale';
import { localizedResponse } from '../_lib/localizedResponse';

const workExperienceByLocale: Record<MainPageLocale, ExperienceItem[]> = {
	en: [
		{
			role: 'Frontend Developer',
			company: 'NomadGames',
			employmentType: 'Full-time',
			period: 'Sep 2024 - Apr 2026',
			duration: '1 year 8 months',
			location: 'Bishkek, Kyrgyzstan',
			mode: 'Product platform',
			stack: [
				'React',
				'TypeScript',
				'FSD',
				'Zustand',
				'TanStack Query',
				'Centrifugo',
				'WebSockets',
				'Tailwind CSS',
			],
			description:
				'Built the frontend of a free browser multiplayer games platform from scratch: application architecture, UI, state management, API integrations and real-time behavior. Designed reusable managers for sound, vibration, asset loading and screen state, and aligned API contracts with the backend team before new features were implemented.',
		},
		{
			role: 'Frontend Developer',
			company: 'DATAxWAY',
			employmentType: 'Full-time',
			period: 'Aug 2023 - Jun 2024',
			duration: '11 months',
			location: 'Bishkek, Kyrgyzstan',
			mode: 'Office',
			stack: [
				'Next.js',
				'React',
				'TypeScript',
				'FSD',
				'TanStack Query',
				'Zustand',
				'Tailwind CSS',
				'REST API',
			],
			description:
				'Delivered e-commerce products, marketplace platforms, SEO-oriented sites and business admin panels. Implemented SSR, SSG and ISR pages, optimized image and font loading for stronger FCP/LCP, and decomposed monolithic UI modules into reusable UI-kit components.',
		},
		{
			role: 'Frontend Developer',
			company: 'GetByVerto',
			employmentType: 'Full-time',
			period: 'Aug 2022 - Aug 2023',
			duration: '1 year 1 month',
			location: 'Remote',
			mode: 'Remote',
			stack: [
				'Next.js',
				'React',
				'TypeScript',
				'Orval',
				'TanStack Query',
				'Zustand',
				'Tailwind CSS',
				'REST API',
			],
			description:
				'Developed the frontend for a marketplace with auctions, chats and barter-based deals. Built a typed API layer with Orval, configured TanStack Query caching and invalidation, and extracted repeated marketplace logic into reusable components and modules.',
		},
		{
			role: 'Frontend Developer',
			company: 'Welive Turkish Company',
			employmentType: 'Full-time',
			period: 'Jan 2022 - Jul 2022',
			duration: '7 months',
			location: 'Bishkek, Kyrgyzstan',
			mode: 'Office',
			stack: [
				'Next.js',
				'React',
				'TypeScript',
				'Redux Toolkit',
				'Material UI',
				'SCSS',
				'REST API',
			],
			description:
				'Worked on an e-commerce platform for home goods and room fragrance products. Implemented catalog pages, product cards, forms, tables and admin sections, including role-based interfaces for different access levels.',
		},
		{
			role: 'Frontend Developer',
			company: 'Budgeting OAPiSR',
			employmentType: 'Contract',
			period: 'Oct 2021 - Jan 2022',
			duration: '4 months',
			location: 'Bishkek, Kyrgyzstan',
			mode: 'Remote',
			stack: [
				'React',
				'Next.js',
				'Ant Design',
				'Styled Components',
				'REST API',
			],
			description:
				'Built interfaces for an internal banking budgeting system with tables, formulas, calculated data and branch structure. Implemented complex table scenarios, optimized large tables and tree structures, and handled validation errors, slow requests and non-standard UI states.',
		},
	],
	ru: [
		{
			role: 'Frontend-разработчик',
			company: 'NomadGames',
			employmentType: 'Полная занятость',
			period: 'Сентябрь 2024 - апрель 2026',
			duration: '1 год 8 месяцев',
			location: 'Бишкек, Кыргызстан',
			mode: 'Продуктовая платформа',
			stack: [
				'React',
				'TypeScript',
				'FSD',
				'Zustand',
				'TanStack Query',
				'Centrifugo',
				'WebSockets',
				'Tailwind CSS',
			],
			description:
				'Разрабатывал frontend веб-платформы для бесплатных браузерных multiplayer-игр с нуля: архитектуру приложения, UI, управление состоянием, API-интеграции и real-time взаимодействие. Реализовывал переиспользуемые менеджеры звука, вибраций, загрузки ассетов и состояния экрана, а также заранее прорабатывал API-контракты с backend-командой.',
		},
		{
			role: 'Frontend-разработчик',
			company: 'DATAxWAY',
			employmentType: 'Полная занятость',
			period: 'Август 2023 - июнь 2024',
			duration: '11 месяцев',
			location: 'Бишкек, Кыргызстан',
			mode: 'Офис',
			stack: [
				'Next.js',
				'React',
				'TypeScript',
				'FSD',
				'TanStack Query',
				'Zustand',
				'Tailwind CSS',
				'REST API',
			],
			description:
				'Работал над e-commerce, marketplace-платформами, SEO-ориентированными сайтами и административными панелями для бизнеса. Реализовывал SSR/SSG/ISR-страницы на Next.js, оптимизировал загрузку изображений и шрифтов для FCP/LCP, декомпозировал монолитные UI-модули в переиспользуемые UI-kit компоненты.',
		},
		{
			role: 'Frontend-разработчик',
			company: 'GetByVerto',
			employmentType: 'Полная занятость',
			period: 'Август 2022 - август 2023',
			duration: '1 год 1 месяц',
			location: 'Удаленно',
			mode: 'Удаленно',
			stack: [
				'Next.js',
				'React',
				'TypeScript',
				'Orval',
				'TanStack Query',
				'Zustand',
				'Tailwind CSS',
				'REST API',
			],
			description:
				'Разрабатывал frontend marketplace-платформы с аукционами, чатами и бартерной моделью сделок. Реализовал типизированный API-слой через Orval, настроил кэширование и инвалидацию данных через TanStack Query, выносил повторяющуюся marketplace-логику в переиспользуемые компоненты и модули.',
		},
		{
			role: 'Frontend-разработчик',
			company: 'Welive Turkish Company',
			employmentType: 'Полная занятость',
			period: 'Январь 2022 - июль 2022',
			duration: '7 месяцев',
			location: 'Бишкек, Кыргызстан',
			mode: 'Офис',
			stack: [
				'Next.js',
				'React',
				'TypeScript',
				'Redux Toolkit',
				'Material UI',
				'SCSS',
				'REST API',
			],
			description:
				'Работал над e-commerce платформой для продажи товаров для дома и ароматизации помещений. Реализовывал страницы каталога, карточки товаров, формы, таблицы и административные разделы, включая интерфейсы для разных уровней доступа.',
		},
		{
			role: 'Frontend-разработчик',
			company: 'Budgeting OAPiSR',
			employmentType: 'Контракт',
			period: 'Октябрь 2021 - январь 2022',
			duration: '4 месяца',
			location: 'Бишкек, Кыргызстан',
			mode: 'Удаленно',
			stack: [
				'React',
				'Next.js',
				'Ant Design',
				'Styled Components',
				'REST API',
			],
			description:
				'Разрабатывал интерфейсы для внутренней банковской системы бюджетирования с таблицами, формулами, расчетными данными и филиальной структурой. Реализовывал сложные табличные сценарии, оптимизировал большие таблицы и древовидные структуры, обрабатывал ошибки валидации, медленные запросы и нестандартные состояния интерфейса.',
		},
	],
};

export const getWorkExperienceResponse = (request: Request) =>
	localizedResponse(request, workExperienceByLocale);
